    CREATE TABLE app_user
    (
        id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        username VARCHAR(255),
        password VARCHAR(255),
        email    VARCHAR(255),
        CONSTRAINT pk_appuser PRIMARY KEY (id)
    );

    CREATE TABLE app_user_roles
    (
        app_user_id INTEGER NOT NULL,
        roles       VARCHAR(255)
    );

    CREATE TABLE item
    (
        item_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name         VARCHAR(255),
        description  VARCHAR(255),
        active       BOOLEAN,
        approved     BOOLEAN,
        winnerid     INTEGER,
        app_user_id  INTEGER,
        image        BYTEA,
        starting_bid DOUBLE PRECISION,
        end_time     TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_item PRIMARY KEY (item_id)
    );

    ALTER TABLE item
        ADD CONSTRAINT FK_ITEM_ON_APP_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

    ALTER TABLE app_user_roles
        ADD CONSTRAINT fk_appuser_roles_on_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id);